services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ativa hot-reload no Docker
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
